### PR TITLE
Update how.are.you.dialog

### PR DESCRIPTION
**Pull request by 12buntu**
More responses to how are you

### CODE REVIEW

**Comment by forslund** [comment]
Hi @12buntu thanks for the contributions, looks good! Before merging your changes we require a Contributor Licensing Agreement (CLA).

This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by penrods** [comment]
Ping on the CLA!

**Comment by KathyReid** [comment]
Hi @12buntu how did you go with the CLA?
Best, Kathy

**Comment by forslund** [comment]
I see you in the list of contributors now so I'll go ahead and merge this oldie. Thank you for adding to the mycroft user experience!

**Pull request merged**
